MiPrimerCRUD/Controllers/LinqController.cs
using Microsoft.AspNetCore.Mvc;
using MiPrimerCRUD.Models;
using MiPrimerCRUD.Services;
using System.Linq;

namespace MiPrimerCRUD.Controllers
{
    public class LinqController : Controller


        
    {

        private MiContexto ctx;
        private IGeneralService general;

        public LinqController(MiContexto ctx, IGeneralService general)
        {
            this.ctx = ctx;
            this.general = general;
        }

        public IActionResult Index(string? filtro)
        {
            var listado = ctx.Asignaturas
                .Where(asig => asig.Nombre.Contains(filtro))
                .OrderByDescending(asig => asig.Id)
                .Take(4);

            ViewBag.filtro = filtro;
            return View(listado);
        }

        public IActionResult ListaCursos(string? filtro, DateTime? fechaDesde, DateTime? fechaHasta)
        {

            var listadoCursos = ctx.Cursos
                                   .Where(cur => cur.Activo == true);


            if (filtro != null)
            {
                listadoCursos = listadoCursos.Where(cur => cur.Nombre.Contains(filtro));
            }
            if (fechaDesde != null)
            {
                listadoCursos = listadoCursos.Where(cur => DateTime.Compare(cur.FechaInicio.Value, fechaDesde.Value) >= 0);
            }
            if(fechaHasta != null)
            {
                listadoCursos = listadoCursos.Where(cur => DateTime.Compare(cur.FechaInicio.Value, fechaHasta.Value) <= 0);
            }
            
            listadoCursos = listadoCursos.OrderByDescending(cur => cur.Id)
                                         .Take(3);
            
            ViewBag.filtro = filtro;
            ViewBag.fechaDesde = fechaDesde?.ToString("yyyy-MM-dd");
            ViewBag.fechaHasta = fechaHasta?.ToString("yyyy-MM-dd");
            ViewBag.autor = general.GetAutor();

            return View(listadoCursos);
        }
    }
}

MiPrimerCRUD/Views/Linq/Index.cshtml
@model IQueryable<Asignatura>


<h1>Ejemplo LINQ</h1>

<form asp-controller="Linq" asp-action="Index" method="GET">
    <input name="filtro" value="@ViewBag.filtro"/>
    <button class="btn btn-primary" type="submit">Enviar</button>
</form>

<table class="table table-striped">

    @foreach (var asig in Model){

        <tr>
            <td>@asig.Id</td>
            <td>@asig.Nombre</td>
            <td>@asig.Cursillo?.Nombre</td>
        </tr>
    }

</table>

MiPrimerCRUD/Views/Linq/ListaCursos.cshtml
@model IQueryable<Curso>


@{

   Layout = "_Secundario";
}

<h1>LISTADO DE CURSOS</h1>

<h5>@ViewBag.autor</h5>

<form asp-controller="Linq" asp-action="ListaCursos" method="GET">
   <div class="row">

       <div class="col-md-4">
           <label>Filtro:</label>
            <input name="filtro" value="@ViewBag.filtro" class="form-control" />
       </div>

        <div class="col-md-4">
            <label>Fecha Desde:</label>
            <input type="date" name="fechaDesde" value="@ViewBag.fechaDesde" class="form-control" />
        </div>

        <div class="col-md-4">
            <label>Fecha Hasta:</label>
            <input type="date" name="fechaHasta" value="@ViewBag.fechaHasta" class="form-control" />
        </div>
       
   </div> 
   
    <button class="btn btn-primary" type="submit">Enviar</button>
</form>

<table class="table table-striped">

    @foreach (var cur in Model)
    {

        <tr>
            <td>@cur.Id</td>
            <td>@cur.Nombre</td>
            <td>@cur.Lugar</td>
            <td>@cur.FechaInicio</td>
            <td>@cur.Activo</td>
        </tr>
    }

</table>